language: node_js
node_js:
  - '10.11.0'
install:
  - cd ./backend
  - npm install
before_script:
  - export COVERAGE_TOKEN=$COVERAGE_TOKEN
script:
  - npm run write-coveralls
  - npm test
notifications:
  email: false
